# Generated by Django 2.2.6 on 2019-11-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Club'),
        ),
    ]
