# Generated by Django 2.2.6 on 2019-11-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20191102_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
