# Generated by Django 2.2.6 on 2019-11-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20191102_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='option',
        ),
        migrations.RemoveField(
            model_name='market',
            name='runners',
        ),
        migrations.RemoveField(
            model_name='market',
            name='type',
        ),
        migrations.CreateModel(
            name='MarketPlacing',
            fields=[
                ('market_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='betting.Market')),
                ('placing', models.IntegerField()),
                ('runners', models.ManyToManyField(to='betting.Runner')),
            ],
            bases=('betting.market',),
        ),
        migrations.CreateModel(
            name='BetPlacing',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='betting.Bet')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Runner')),
            ],
            bases=('betting.bet',),
        ),
    ]
