# Generated by Django 2.2.6 on 2019-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_auto_20191104_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacing',
            name='runners',
        ),
        migrations.AddField(
            model_name='competition',
            name='competitors',
            field=models.ManyToManyField(to='betting.Competitor'),
        ),
    ]
