# Generated by Django 2.2.6 on 2019-11-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_punter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betplacing',
            old_name='runner',
            new_name='competitor',
        ),
    ]
