# Generated by Django 2.2.6 on 2019-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0010_auto_20191106_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='location',
        ),
    ]
