# Generated by Django 2.2.6 on 2019-11-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0012_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='betting.Event'),
            preserve_default=False,
        ),
    ]
